
package view;

import excecao.Excecao;
import java.util.ArrayList;
import java.util.Enumeration;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;
import model.Medicamento;

/**
 *
 * @author Luis Gustavo
 */
public class FormularioCadastroMedicamento extends javax.swing.JFrame {

    private final List<Medicamento> medicamentos;
    private Medicamento medicamento;
    
    public FormularioCadastroMedicamento() {
        this.medicamentos = new ArrayList<>();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grTipo = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lbCodigoBarra = new javax.swing.JLabel();
        tfCodigoBarra = new javax.swing.JTextField();
        lbNome = new javax.swing.JLabel();
        tfNome = new javax.swing.JTextField();
        lbLaboratorio = new javax.swing.JLabel();
        lbValorUnitario = new javax.swing.JLabel();
        tfValorUnitario = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        rbAnsiolitico = new javax.swing.JRadioButton();
        rbAntibiotico = new javax.swing.JRadioButton();
        rbAnalgesico = new javax.swing.JRadioButton();
        rbHormonal = new javax.swing.JRadioButton();
        rbPolivitaminico = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        taComposicao = new javax.swing.JTextArea();
        tfLaboratorio = new javax.swing.JTextField();
        lbQuantidade = new javax.swing.JLabel();
        tfQuantidade = new javax.swing.JTextField();
        lbLocalizacao = new javax.swing.JLabel();
        cbLocalizacao = new javax.swing.JComboBox<>();
        btInserir = new javax.swing.JButton();
        btBuscar = new javax.swing.JButton();
        btVender = new javax.swing.JButton();
        btSair = new javax.swing.JButton();
        btLimpar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Medicamento");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Cadastro", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        lbCodigoBarra.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbCodigoBarra.setText("*Código de Barra:");

        lbNome.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbNome.setText("*Nome:");

        lbLaboratorio.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbLaboratorio.setText("*Laboratório:");

        lbValorUnitario.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbValorUnitario.setText("*Valor Unitário:");

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Tipo", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        grTipo.add(rbAnsiolitico);
        rbAnsiolitico.setText("Ansiolítico");

        grTipo.add(rbAntibiotico);
        rbAntibiotico.setText("Antibiótico");

        grTipo.add(rbAnalgesico);
        rbAnalgesico.setSelected(true);
        rbAnalgesico.setText("Analgésico");

        grTipo.add(rbHormonal);
        rbHormonal.setText("Hormonal");

        grTipo.add(rbPolivitaminico);
        rbPolivitaminico.setText("Polivitamínico");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rbAnsiolitico)
                .addGap(10, 10, 10)
                .addComponent(rbAntibiotico)
                .addGap(18, 18, 18)
                .addComponent(rbAnalgesico)
                .addGap(18, 18, 18)
                .addComponent(rbHormonal)
                .addGap(18, 18, 18)
                .addComponent(rbPolivitaminico)
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbAnsiolitico)
                    .addComponent(rbAntibiotico)
                    .addComponent(rbAnalgesico)
                    .addComponent(rbHormonal)
                    .addComponent(rbPolivitaminico))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jScrollPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Composição", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        taComposicao.setColumns(20);
        taComposicao.setRows(5);
        jScrollPane1.setViewportView(taComposicao);

        lbQuantidade.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbQuantidade.setText("*Quantidade:");

        lbLocalizacao.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbLocalizacao.setText("Localização:");

        cbLocalizacao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lbCodigoBarra)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfCodigoBarra, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lbNome)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfNome, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lbLaboratorio)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfLaboratorio, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                    .addComponent(lbLocalizacao)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(cbLocalizacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                    .addComponent(lbQuantidade)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(tfQuantidade))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                    .addComponent(lbValorUnitario)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(tfValorUnitario, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbCodigoBarra)
                    .addComponent(tfCodigoBarra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNome)
                    .addComponent(tfNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbLaboratorio)
                    .addComponent(tfLaboratorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbValorUnitario)
                    .addComponent(tfValorUnitario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbQuantidade)
                    .addComponent(tfQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbLocalizacao)
                    .addComponent(cbLocalizacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btInserir.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btInserir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/inserir.png"))); // NOI18N
        btInserir.setMnemonic('i');
        btInserir.setText("Inserir");
        btInserir.setMaximumSize(new java.awt.Dimension(107, 39));
        btInserir.setPreferredSize(new java.awt.Dimension(107, 39));
        btInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btInserirActionPerformed(evt);
            }
        });

        btBuscar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/buscar.png"))); // NOI18N
        btBuscar.setMnemonic('b');
        btBuscar.setText("Buscar");
        btBuscar.setMaximumSize(new java.awt.Dimension(107, 39));
        btBuscar.setPreferredSize(new java.awt.Dimension(107, 39));
        btBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBuscarActionPerformed(evt);
            }
        });

        btVender.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btVender.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/vender.png"))); // NOI18N
        btVender.setMnemonic('v');
        btVender.setText("Vender");
        btVender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVenderActionPerformed(evt);
            }
        });

        btSair.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/sair.png"))); // NOI18N
        btSair.setMnemonic('s');
        btSair.setText("Sair");
        btSair.setMaximumSize(new java.awt.Dimension(107, 39));
        btSair.setPreferredSize(new java.awt.Dimension(107, 39));
        btSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairActionPerformed(evt);
            }
        });

        btLimpar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/limpar.png"))); // NOI18N
        btLimpar.setMnemonic('l');
        btLimpar.setText("Limpar");
        btLimpar.setMaximumSize(new java.awt.Dimension(107, 39));
        btLimpar.setPreferredSize(new java.awt.Dimension(107, 39));
        btLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btInserir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btVender)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btSair, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btInserir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btVender)
                    .addComponent(btSair, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(613, 569));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairActionPerformed
        this.dispose();
    }//GEN-LAST:event_btSairActionPerformed

    private void btInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btInserirActionPerformed
        try{
            String codigoBarra = tfCodigoBarra.getText();
            String nome = tfNome.getText();
            String laboratorio = tfLaboratorio.getText();
            double valorUnitario = Double.parseDouble(tfValorUnitario.getText());
            int quantidade = Integer.parseInt(tfQuantidade.getText());
            String localizacao = cbLocalizacao.getSelectedItem().toString();
            String composicao = taComposicao.getText();
            String tipo = capturarRadio();
            medicamento = new Medicamento(codigoBarra, nome, laboratorio, valorUnitario, composicao,
            tipo, quantidade, localizacao);
            medicamentos.add(medicamento);
            JOptionPane.showMessageDialog(null, "Medicamento cadastrado com sucesso!", "Finalizado!", 
            JOptionPane.INFORMATION_MESSAGE);
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null, "Preencha todos os campos!", "Atenção!", 
            JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btInserirActionPerformed

    private void btBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBuscarActionPerformed
        String nome = tfNome.getText();
        String codigoBarra = tfCodigoBarra.getText();
        medicamento = buscarPorNome(nome);
        if(medicamento != null){
            preencherCampos(medicamento.getCodigoBarra(), medicamento.getNome(), 
            medicamento.getLaboratorio(), Double.toString(medicamento.getValorUnitario()),
            Integer.toString(medicamento.getQuantidadeEstoque()), 
            medicamento.getLocalizacao(),medicamento.getComposicao(), 
            medicamento.getTipo());
        }else{
            medicamento = buscarPorCodigo(codigoBarra);
            if(medicamento != null){
                 preencherCampos(medicamento.getCodigoBarra(), medicamento.getNome(), 
                 medicamento.getLaboratorio(), Double.toString(medicamento.getValorUnitario()),
                 Integer.toString(medicamento.getQuantidadeEstoque()), 
                 medicamento.getLocalizacao(),medicamento.getComposicao(), 
                 medicamento.getTipo());
            }else{
                JOptionPane.showMessageDialog(null, "Medicamento não encontrado!", "Atenção!", 
                JOptionPane.INFORMATION_MESSAGE);
            }
        }
    }//GEN-LAST:event_btBuscarActionPerformed

    private void btVenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVenderActionPerformed
        try{
            int quantidade = Integer.parseInt(JOptionPane.showInputDialog(null, "Informe a quantidade a ser "
            + "comprada!", "Atenção!", JOptionPane.QUESTION_MESSAGE));
            medicamento.locar(quantidade);
            double valorTotalVenda = medicamento.calcularVatorTotalVenda(quantidade);
            JOptionPane.showMessageDialog(null, "Venda finalizada com valor de R$ " + valorTotalVenda);
        }catch(NumberFormatException ex){
            JOptionPane.showMessageDialog(null, "Informe apenas número!", "Atenção!",
            JOptionPane.WARNING_MESSAGE);
        }catch (Excecao ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }catch(NullPointerException ex){
           JOptionPane.showMessageDialog(null, "Busque um medicamento primeiro!", "Atenção!", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btVenderActionPerformed

    private void btLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparActionPerformed
        tfCodigoBarra.setText("");
        tfNome.setText("");
        tfLaboratorio.setText("");
        tfValorUnitario.setText("");
        tfQuantidade.setText("");
        cbLocalizacao.setSelectedIndex(0);
        taComposicao.setText("");
        grTipo.clearSelection();
        rbAnalgesico.setSelected(true);
        tfCodigoBarra.requestFocus();
    }//GEN-LAST:event_btLimparActionPerformed

    private String capturarRadio(){
        JRadioButton radio;
        String str = null;
        Enumeration jr = grTipo.getElements();
        while ( jr.hasMoreElements() )
        {
            radio = (JRadioButton) jr.nextElement();
            if (radio.isSelected())
            {
                str = radio.getText();
            }
        }
        return str;
    }
    
    private void marcarRadio(String str){
        JRadioButton radio;
        Enumeration jr = grTipo.getElements();
        while ( jr.hasMoreElements() ) {
            radio = (JRadioButton) jr.nextElement();
            if (radio.getText().equals(str))
                radio.setSelected(true);
        }
    }
    
    private void preencherCampos(String codigoBarra, String nome, String laboratorio, 
    String valorUnitario, String quantidade, String localizacao, String composicao, String tipo){
        tfCodigoBarra.setText(codigoBarra);
        tfNome.setText(nome);
        tfLaboratorio.setText(laboratorio);
        tfValorUnitario.setText(valorUnitario);
        tfQuantidade.setText(quantidade);
        cbLocalizacao.setSelectedItem(localizacao);
        taComposicao.setText(composicao);
        marcarRadio(tipo);
    }
  
    private Medicamento buscarPorNome(String nome){
        Medicamento med = null;
        for(Medicamento m : medicamentos){
            if(m.getNome().equals(nome)){
                med = m;
            }
        }
        return med;
    }
    
    private Medicamento buscarPorCodigo(String codigo){
        Medicamento med = null;
        for(Medicamento m : medicamentos){
            if(m.getCodigoBarra().equals(codigo)){
                med = m;
            }
        }
        return med;
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormularioCadastroMedicamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormularioCadastroMedicamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormularioCadastroMedicamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormularioCadastroMedicamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormularioCadastroMedicamento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btBuscar;
    private javax.swing.JButton btInserir;
    private javax.swing.JButton btLimpar;
    private javax.swing.JButton btSair;
    private javax.swing.JButton btVender;
    private javax.swing.JComboBox<String> cbLocalizacao;
    private javax.swing.ButtonGroup grTipo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbCodigoBarra;
    private javax.swing.JLabel lbLaboratorio;
    private javax.swing.JLabel lbLocalizacao;
    private javax.swing.JLabel lbNome;
    private javax.swing.JLabel lbQuantidade;
    private javax.swing.JLabel lbValorUnitario;
    private javax.swing.JRadioButton rbAnalgesico;
    private javax.swing.JRadioButton rbAnsiolitico;
    private javax.swing.JRadioButton rbAntibiotico;
    private javax.swing.JRadioButton rbHormonal;
    private javax.swing.JRadioButton rbPolivitaminico;
    private javax.swing.JTextArea taComposicao;
    private javax.swing.JTextField tfCodigoBarra;
    private javax.swing.JTextField tfLaboratorio;
    private javax.swing.JTextField tfNome;
    private javax.swing.JTextField tfQuantidade;
    private javax.swing.JTextField tfValorUnitario;
    // End of variables declaration//GEN-END:variables
}
